language: node_js
sudo: true
os:
- linux
- osx
cache:
  directories:
  - node_modules
  - "/usr/local/Cellar"
node_js:
- '8'
addons:
  apt:
    packages:
      - fakeroot
before_script:
- if [[ -n "$TRAVIS_TAG" ]]; then if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "./.travis/add-key.sh"; fi ; fi
script:
- npm run lint
- npm run test
- if [ -n "$TRAVIS_TAG" ]; then ./build.sh; fi
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - "dist/win32/*.exe"
    - "dist/win32/*.nupkg"
    - "dist/win32/RELEASES"
    - "dist/win64/*.exe"
    - "dist/win64/*.nupkg"
    - "dist/osx/*.dmg"
    - "dist/osx/*.zip"
    - "dist/linux32/*.deb"
    - "dist/linux64/*.deb"
    - "dist/linux32/*.rpm"
    - "dist/linux64/*.rpm"
  skip_cleanup: true
  all_branches: true
  on:
    tags: true
env:
  global:
  - secure: QOLIgDAmXZab6HZHnZK0wrbhoblEY7A8ddVK34dm+/lIxtt0E504O+xidsSgKSUJhehHSlBwd9TlI01AIuznBlfSCq9pvzaM/F+ppidN4mk6XE0ymFJMgpS5E2+CGiz1/CpOLK2GkF3Mf1nOHLNDL3UvysE60cZcqwZV+lL8kI+Z61TUy7JfK6Ev77WIheuumVIm3ybnVH5vPdkLVi/nxR1qL3xPB7HVC/fZF7s1D3qaMijO1rK0pHBvgQ7JCF09Bq6WyEdTITlsXfY5ttMi7Szfu6NuiXtn646jsGeVOswCUR18BlzjWNUgrvmfqPhY6FMaKRe0L+tTlNkoZKixLQ2PrvRlpY/9PdTrjXh6izOnzzXY5AqFW7Tt3tAAU8y3LLOoMeUn4cB7rtqr2X5q1T75yTp61H6kTMUDX2nmXWCKMgcu4QtciW5rC1LCvU2FN5Y2WE+wlFyiqMw85krmFt8PHMsi+NRVGAFaI5CMRoi8eFXK9mZeUgDe1wFKPSyvElerE+NCc7pKSTVJxkFLdV/htHo6MGYXKxGQOVwN9CJjDKlKN6pd5u/7PLq7vp+5LaVpefKzJQZvFZy9x39aP0H2yOsDeNKROfmbOc/k3/1lCVGYiisPeVxLNrth9b0c1mBEg3bqWv0aLa329mP/YjQeOjlqFsBkSfeEoxdO7yw=
  - secure: Pe1V7KTN2oQxPS86jVrsl6sau9sfHfvS76hTTkTH+zw9bw5clQrcZyIzEBRzoEZJAcUfXD8LpzVvdevQQdRQCXZokVzR57SyRLt7/8ZTthvICr3olRNNSQ2KuJvmZddpZZtPQBHiUTG8KsAcCJiwo9kjthD7bb10zGCzTeYCxURq9YSD4pBRjEaB2fBfp030FTyO2RqjDGwKpI2AGTMOMq98HbDsq712kHgsUd6Td+aOpY6ZOpIzisdX4pkTNQdt+IgKJAdvIUsxzM+IjXj9cc3GAJTVx4kbVBJGykQvjcN8T4Xuj0X+rxg4DxGEJhOTL2RHqtLpCsxS9KWAOcKmXIxwbMgd0EmR5f12peMqsvVNTHE7GIeThDJSNWmIlEgOoEyvTNHo+NNy/4AeTlarWEoODfLte7IKXXC0XPFfglRtGAxKqn4AVQ5Hd2eorCPU3nKGNV4yHL3D7etRuh/+YuN4xE74g1WwA+q+NpL8UNn697HJA2rjAeY4Pij+VWMBOAQnjX11CDiBk4paDVi0WAVht+0Ol1InFf/LpkOA1W6+F5PXlLEANFnMEtjpJL7SLPg4kLdtqTF/coYv821JLJEOh0v3UCtu/gTEBx5/XLP2bvDI3IgF31xN2X7R3075H9cevjLyRMNmGq5pbkuPIJTnQVL0vwq0e5qxrJzAhEQ=
